import { Product, ProductDetail, ProductCategory, InhaleType } from '@/types/product';

// 액상 상품 30개
const liquidProducts: ProductDetail[] = [
  // MTL 액상 15개
  {
    id: 'liquid-001',
    name: '[SMOANT] 바닐라 카페라떼 30ml',
    price: 2800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=바닐라카페라떼',
    inhaleType: InhaleType.MTL,
    flavor: '바닐라',
    capacity: '30ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=바닐라카페라떼',
    productCategory: ProductCategory.LIQUID,
    totalViews: 324,
    totalFavorites: 87,
    weeklyViews: 45,
    brand: 'SMOANT',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 4.6, menthol: 3.2, throatHit: 2.1, body: 3.5, freshness: 4.0, totalReviewCount: 12 },
    sellers: [{ name: '베이프월드', price: 2800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 2800 }],
  },
  {
    id: 'liquid-002',
    name: '[VGOD] SaltNic 레몬 아이스 50ml',
    price: 3500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=레몬아이스',
    inhaleType: InhaleType.MTL,
    flavor: '레몬',
    capacity: '50ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=레몬아이스',
    productCategory: ProductCategory.LIQUID,
    totalViews: 456,
    totalFavorites: 132,
    weeklyViews: 68,
    brand: 'VGOD',
    isAvailable: true,
    averageReviewInfo: { rating: 4.7, sweetness: 2.8, menthol: 4.9, throatHit: 3.2, body: 2.8, freshness: 4.8, totalReviewCount: 24 },
    sellers: [{ name: '전자담배샵', price: 3500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 3500 }],
  },
  {
    id: 'liquid-003',
    name: '[Nasty Juice] 청포도 솔트 30ml',
    price: 4200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=청포도솔트',
    inhaleType: InhaleType.MTL,
    flavor: '포도',
    capacity: '30ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=청포도솔트',
    productCategory: ProductCategory.LIQUID,
    totalViews: 289,
    totalFavorites: 98,
    weeklyViews: 52,
    brand: 'Nasty Juice',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 4.2, menthol: 1.5, throatHit: 2.8, body: 3.1, freshness: 3.9, totalReviewCount: 18 },
    sellers: [{ name: '베이프마켓', price: 4200, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 4200 }],
  },
  {
    id: 'liquid-004',
    name: '[Dinner Lady] 딸기 쿠키 30ml',
    price: 3800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=딸기쿠키',
    inhaleType: InhaleType.MTL,
    flavor: '딸기',
    capacity: '30ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=딸기쿠키',
    productCategory: ProductCategory.LIQUID,
    totalViews: 567,
    totalFavorites: 143,
    weeklyViews: 89,
    brand: 'Dinner Lady',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 4.8, menthol: 0.5, throatHit: 1.9, body: 3.8, freshness: 3.2, totalReviewCount: 31 },
    sellers: [{ name: '쿨베이퍼', price: 3800, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 3800 }],
  },
  {
    id: 'liquid-005',
    name: '[PACHA MAMA] 망고 패션후르츠 60ml',
    price: 5200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=망고패션후르츠',
    inhaleType: InhaleType.MTL,
    flavor: '망고',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=망고패션후르츠',
    productCategory: ProductCategory.LIQUID,
    totalViews: 712,
    totalFavorites: 189,
    weeklyViews: 125,
    brand: 'PACHA MAMA',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 4.3, menthol: 2.1, throatHit: 2.5, body: 3.6, freshness: 4.2, totalReviewCount: 42 },
    sellers: [{ name: '익스트림베이프', price: 5200, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 5200 }],
  },
  {
    id: 'liquid-006',
    name: '[JUUL] 클래식 담배맛 10ml',
    price: 2200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=클래식담배',
    inhaleType: InhaleType.MTL,
    flavor: '담배',
    capacity: '10ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=클래식담배',
    productCategory: ProductCategory.LIQUID,
    totalViews: 445,
    totalFavorites: 76,
    weeklyViews: 67,
    brand: 'JUUL',
    isAvailable: true,
    averageReviewInfo: { rating: 3.8, sweetness: 1.2, menthol: 1.8, throatHit: 4.2, body: 4.1, freshness: 2.5, totalReviewCount: 28 },
    sellers: [{ name: '베이프월드', price: 2200, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 2200 }],
  },
  {
    id: 'liquid-007',
    name: '[Salt Bae] 블루베리 치즈케이크 30ml',
    price: 4500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=블루베리치즈케이크',
    inhaleType: InhaleType.MTL,
    flavor: '블루베리',
    capacity: '30ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=블루베리치즈케이크',
    productCategory: ProductCategory.LIQUID,
    totalViews: 356,
    totalFavorites: 112,
    weeklyViews: 71,
    brand: 'Salt Bae',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 4.7, menthol: 0.8, throatHit: 2.3, body: 3.9, freshness: 3.4, totalReviewCount: 19 },
    sellers: [{ name: '전자담배샵', price: 4500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 4500 }],
  },
  {
    id: 'liquid-008',
    name: '[Pod Salt] 애플 아이스 10ml',
    price: 3200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=애플아이스',
    inhaleType: InhaleType.MTL,
    flavor: '사과',
    capacity: '10ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=애플아이스',
    productCategory: ProductCategory.LIQUID,
    totalViews: 523,
    totalFavorites: 145,
    weeklyViews: 94,
    brand: 'Pod Salt',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 3.6, menthol: 4.1, throatHit: 2.7, body: 3.2, freshness: 4.5, totalReviewCount: 35 },
    sellers: [{ name: '베이프마켓', price: 3200, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 3200 }],
  },
  {
    id: 'liquid-009',
    name: '[IVG] 라즈베리 레모네이드 10ml',
    price: 2900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=라즈베리레모네이드',
    inhaleType: InhaleType.MTL,
    flavor: '라즈베리',
    capacity: '10ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=라즈베리레모네이드',
    productCategory: ProductCategory.LIQUID,
    totalViews: 234,
    totalFavorites: 67,
    weeklyViews: 41,
    brand: 'IVG',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 4.1, menthol: 2.8, throatHit: 2.4, body: 3.3, freshness: 4.3, totalReviewCount: 15 },
    sellers: [{ name: '쿨베이퍼', price: 2900, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 2900 }],
  },
  {
    id: 'liquid-010',
    name: '[Naked 100] 피치 아이스 60ml',
    price: 6800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=피치아이스',
    inhaleType: InhaleType.MTL,
    flavor: '복숭아',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=피치아이스',
    productCategory: ProductCategory.LIQUID,
    totalViews: 889,
    totalFavorites: 234,
    weeklyViews: 156,
    brand: 'Naked 100',
    isAvailable: true,
    averageReviewInfo: { rating: 4.8, sweetness: 4.2, menthol: 4.6, throatHit: 2.1, body: 3.1, freshness: 4.7, totalReviewCount: 56 },
    sellers: [{ name: '익스트림베이프', price: 6800, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 6800 }],
  },
  {
    id: 'liquid-011',
    name: '[Elf Bar] 그린 애플 아이스 20ml',
    price: 2600,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=그린애플아이스',
    inhaleType: InhaleType.MTL,
    flavor: '사과',
    capacity: '20ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=그린애플아이스',
    productCategory: ProductCategory.LIQUID,
    totalViews: 412,
    totalFavorites: 89,
    weeklyViews: 73,
    brand: 'Elf Bar',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 3.4, menthol: 4.3, throatHit: 2.6, body: 2.9, freshness: 4.4, totalReviewCount: 23 },
    sellers: [{ name: '베이프월드', price: 2600, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 2600 }],
  },
  {
    id: 'liquid-012',
    name: '[Candy King] 수박 사워벨트 100ml',
    price: 8900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=수박사워벨트',
    inhaleType: InhaleType.MTL,
    flavor: '수박',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=수박사워벨트',
    productCategory: ProductCategory.LIQUID,
    totalViews: 645,
    totalFavorites: 178,
    weeklyViews: 113,
    brand: 'Candy King',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 4.9, menthol: 1.2, throatHit: 1.8, body: 2.6, freshness: 3.8, totalReviewCount: 38 },
    sellers: [{ name: '전자담배샵', price: 8900, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 8900 }],
  },
  {
    id: 'liquid-013',
    name: '[Vapetasia] 킬러 커스터드 60ml',
    price: 5800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=킬러커스터드',
    inhaleType: InhaleType.MTL,
    flavor: '커스터드',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=킬러커스터드',
    productCategory: ProductCategory.LIQUID,
    totalViews: 512,
    totalFavorites: 134,
    weeklyViews: 92,
    brand: 'Vapetasia',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 4.4, menthol: 0.3, throatHit: 2.0, body: 4.2, freshness: 2.8, totalReviewCount: 29 },
    sellers: [{ name: '베이프마켓', price: 5800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 5800 }],
  },
  {
    id: 'liquid-014',
    name: '[Coastal Clouds] 체리 블라썸 60ml',
    price: 4900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=체리블라썸',
    inhaleType: InhaleType.MTL,
    flavor: '체리',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=체리블라썸',
    productCategory: ProductCategory.LIQUID,
    totalViews: 367,
    totalFavorites: 95,
    weeklyViews: 66,
    brand: 'Coastal Clouds',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 4.0, menthol: 2.5, throatHit: 2.3, body: 3.4, freshness: 3.9, totalReviewCount: 21 },
    sellers: [{ name: '쿨베이퍼', price: 4900, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 4900 }],
  },
  {
    id: 'liquid-015',
    name: '[Twist E-Liquids] 핑크 펀치 레모네이드 60ml',
    price: 5500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=핑크펀치레모네이드',
    inhaleType: InhaleType.MTL,
    flavor: '레몬',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=핑크펀치레모네이드',
    productCategory: ProductCategory.LIQUID,
    totalViews: 428,
    totalFavorites: 116,
    weeklyViews: 78,
    brand: 'Twist E-Liquids',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 4.1, menthol: 3.2, throatHit: 2.2, body: 3.0, freshness: 4.1, totalReviewCount: 26 },
    sellers: [{ name: '익스트림베이프', price: 5500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 5500 }],
  },

  // DL 액상 15개
  {
    id: 'liquid-016',
    name: '[CLOUD NURDZ] 레인보우 그레이프 100ml',
    price: 12000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=레인보우그레이프',
    inhaleType: InhaleType.DL,
    flavor: '포도',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=레인보우그레이프',
    productCategory: ProductCategory.LIQUID,
    totalViews: 789,
    totalFavorites: 201,
    weeklyViews: 134,
    brand: 'CLOUD NURDZ',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 4.5, menthol: 1.8, throatHit: 1.5, body: 2.8, freshness: 3.6, totalReviewCount: 45 },
    sellers: [{ name: '베이프월드', price: 12000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 12000 }],
  },
  {
    id: 'liquid-017',
    name: '[Jam Monster] 스트로베리 잼 100ml',
    price: 11500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=스트로베리잼',
    inhaleType: InhaleType.DL,
    flavor: '딸기',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=스트로베리잼',
    productCategory: ProductCategory.LIQUID,
    totalViews: 934,
    totalFavorites: 267,
    weeklyViews: 167,
    brand: 'Jam Monster',
    isAvailable: true,
    averageReviewInfo: { rating: 4.7, sweetness: 4.8, menthol: 0.5, throatHit: 1.2, body: 3.9, freshness: 3.1, totalReviewCount: 62 },
    sellers: [{ name: '전자담배샵', price: 11500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 11500 }],
  },
  {
    id: 'liquid-018',
    name: '[VAPETASIA] 밀크맨 델럭스 100ml',
    price: 13200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=밀크맨델럭스',
    inhaleType: InhaleType.DL,
    flavor: '밀크',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=밀크맨델럭스',
    productCategory: ProductCategory.LIQUID,
    totalViews: 675,
    totalFavorites: 189,
    weeklyViews: 115,
    brand: 'VAPETASIA',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 4.3, menthol: 0.8, throatHit: 1.6, body: 4.5, freshness: 2.9, totalReviewCount: 41 },
    sellers: [{ name: '베이프마켓', price: 13200, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 13200 }],
  },
  {
    id: 'liquid-019',
    name: '[Humble Juice] 베리 블로우 도넛 120ml',
    price: 15800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=베리블로우도넛',
    inhaleType: InhaleType.DL,
    flavor: '베리',
    capacity: '120ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=베리블로우도넛',
    productCategory: ProductCategory.LIQUID,
    totalViews: 1123,
    totalFavorites: 298,
    weeklyViews: 201,
    brand: 'Humble Juice',
    isAvailable: true,
    averageReviewInfo: { rating: 4.8, sweetness: 4.6, menthol: 1.1, throatHit: 1.3, body: 3.2, freshness: 3.4, totalReviewCount: 73 },
    sellers: [{ name: '쿨베이퍼', price: 15800, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 15800 }],
  },
  {
    id: 'liquid-020',
    name: '[Bad Drip] 세루치 100ml',
    price: 10900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=세루치',
    inhaleType: InhaleType.DL,
    flavor: '시리얼',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=세루치',
    productCategory: ProductCategory.LIQUID,
    totalViews: 456,
    totalFavorites: 123,
    weeklyViews: 82,
    brand: 'Bad Drip',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 4.0, menthol: 0.6, throatHit: 1.8, body: 3.7, freshness: 3.2, totalReviewCount: 34 },
    sellers: [{ name: '익스트림베이프', price: 10900, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 10900 }],
  },
  {
    id: 'liquid-021',
    name: '[Nasty Juice] 아스모 100ml',
    price: 9800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=아스모',
    inhaleType: InhaleType.DL,
    flavor: '복숭아',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=아스모',
    productCategory: ProductCategory.LIQUID,
    totalViews: 623,
    totalFavorites: 167,
    weeklyViews: 109,
    brand: 'Nasty Juice',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 3.9, menthol: 2.3, throatHit: 1.4, body: 3.1, freshness: 4.0, totalReviewCount: 38 },
    sellers: [{ name: '베이프월드', price: 9800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 9800 }],
  },
  {
    id: 'liquid-022',
    name: '[Loaded] 글레이즈 도넛 120ml',
    price: 14500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=글레이즈도넛',
    inhaleType: InhaleType.DL,
    flavor: '도넛',
    capacity: '120ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=글레이즈도넛',
    productCategory: ProductCategory.LIQUID,
    totalViews: 834,
    totalFavorites: 221,
    weeklyViews: 142,
    brand: 'Loaded',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 4.7, menthol: 0.4, throatHit: 1.1, body: 4.1, freshness: 2.8, totalReviewCount: 51 },
    sellers: [{ name: '전자담배샵', price: 14500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 14500 }],
  },
  {
    id: 'liquid-023',
    name: '[Dinner Lady] 레몬 타르트 60ml',
    price: 7800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=레몬타르트',
    inhaleType: InhaleType.DL,
    flavor: '레몬',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=레몬타르트',
    productCategory: ProductCategory.LIQUID,
    totalViews: 512,
    totalFavorites: 145,
    weeklyViews: 91,
    brand: 'Dinner Lady',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 4.2, menthol: 1.8, throatHit: 1.5, body: 3.6, freshness: 3.8, totalReviewCount: 32 },
    sellers: [{ name: '베이프마켓', price: 7800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 7800 }],
  },
  {
    id: 'liquid-024',
    name: '[Air Factory] 블루 라즈베리 100ml',
    price: 11200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=블루라즈베리',
    inhaleType: InhaleType.DL,
    flavor: '라즈베리',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=블루라즈베리',
    productCategory: ProductCategory.LIQUID,
    totalViews: 698,
    totalFavorites: 187,
    weeklyViews: 119,
    brand: 'Air Factory',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 4.1, menthol: 2.6, throatHit: 1.7, body: 2.9, freshness: 4.2, totalReviewCount: 43 },
    sellers: [{ name: '쿨베이퍼', price: 11200, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 11200 }],
  },
  {
    id: 'liquid-025',
    name: '[Bantam] 쿠키 몬스터 60ml',
    price: 8500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=쿠키몬스터',
    inhaleType: InhaleType.DL,
    flavor: '쿠키',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=쿠키몬스터',
    productCategory: ProductCategory.LIQUID,
    totalViews: 445,
    totalFavorites: 119,
    weeklyViews: 78,
    brand: 'Bantam',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 4.4, menthol: 0.7, throatHit: 1.6, body: 3.8, freshness: 2.9, totalReviewCount: 27 },
    sellers: [{ name: '익스트림베이프', price: 8500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 8500 }],
  },
  {
    id: 'liquid-026',
    name: '[FRYD] 후라이드 오레오 120ml',
    price: 16800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=후라이드오레오',
    inhaleType: InhaleType.DL,
    flavor: '오레오',
    capacity: '120ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=후라이드오레오',
    productCategory: ProductCategory.LIQUID,
    totalViews: 923,
    totalFavorites: 256,
    weeklyViews: 165,
    brand: 'FRYD',
    isAvailable: true,
    averageReviewInfo: { rating: 4.7, sweetness: 4.8, menthol: 0.3, throatHit: 1.2, body: 4.3, freshness: 2.6, totalReviewCount: 58 },
    sellers: [{ name: '베이프월드', price: 16800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 16800 }],
  },
  {
    id: 'liquid-027',
    name: '[Cuttwood] 유니콘 밀크 60ml',
    price: 9200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=유니콘밀크',
    inhaleType: InhaleType.DL,
    flavor: '딸기',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=유니콘밀크',
    productCategory: ProductCategory.LIQUID,
    totalViews: 567,
    totalFavorites: 152,
    weeklyViews: 97,
    brand: 'Cuttwood',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 4.3, menthol: 1.2, throatHit: 1.4, body: 3.7, freshness: 3.5, totalReviewCount: 35 },
    sellers: [{ name: '전자담배샵', price: 9200, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 9200 }],
  },
  {
    id: 'liquid-028',
    name: '[KILO] 트루 블루 100ml',
    price: 10500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=트루블루',
    inhaleType: InhaleType.DL,
    flavor: '블루베리',
    capacity: '100ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=트루블루',
    productCategory: ProductCategory.LIQUID,
    totalViews: 389,
    totalFavorites: 103,
    weeklyViews: 68,
    brand: 'KILO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 3.8, menthol: 2.1, throatHit: 1.6, body: 3.2, freshness: 3.9, totalReviewCount: 29 },
    sellers: [{ name: '베이프마켓', price: 10500, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 10500 }],
  },
  {
    id: 'liquid-029',
    name: '[Suicide Bunny] 마더스 밀크 30ml',
    price: 7200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=마더스밀크',
    inhaleType: InhaleType.DL,
    flavor: '커스터드',
    capacity: '30ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=마더스밀크',
    productCategory: ProductCategory.LIQUID,
    totalViews: 456,
    totalFavorites: 128,
    weeklyViews: 79,
    brand: 'Suicide Bunny',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 4.1, menthol: 0.9, throatHit: 1.8, body: 4.0, freshness: 3.1, totalReviewCount: 31 },
    sellers: [{ name: '쿨베이퍼', price: 7200, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 7200 }],
  },
  {
    id: 'liquid-030',
    name: '[VapeWild] 머매이드 송 60ml',
    price: 6800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=머매이드송',
    inhaleType: InhaleType.DL,
    flavor: '열대과일',
    capacity: '60ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=머매이드송',
    productCategory: ProductCategory.LIQUID,
    totalViews: 312,
    totalFavorites: 87,
    weeklyViews: 56,
    brand: 'VapeWild',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 3.9, menthol: 2.8, throatHit: 1.5, body: 3.0, freshness: 4.1, totalReviewCount: 22 },
    sellers: [{ name: '익스트림베이프', price: 6800, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 6800 }],
  },
];

// 기기 상품 20개  
const deviceProducts: ProductDetail[] = [
  // MTL 기기 10개
  {
    id: 'device-001',
    name: '[JUUL] 스타터 키트',
    price: 35000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=JUUL스타터키트',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=JUUL스타터키트',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1245,
    totalFavorites: 289,
    weeklyViews: 218,
    brand: 'JUUL',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 3.5, body: 3.8, freshness: 0, totalReviewCount: 67 },
    sellers: [{ name: '베이프월드', price: 35000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 35000 }],
  },
  {
    id: 'device-002',
    name: '[VAPORESSO] XROS 3 Pod Kit',
    price: 42000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=XROS3',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '1000mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=XROS3',
    productCategory: ProductCategory.DEVICE,
    totalViews: 2134,
    totalFavorites: 456,
    weeklyViews: 363,
    brand: 'VAPORESSO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 0, menthol: 0, throatHit: 4.1, body: 4.3, freshness: 0, totalReviewCount: 89 },
    sellers: [{ name: '전자담배샵', price: 42000, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 42000 }],
  },
  {
    id: 'device-003',
    name: '[SMOK] Nord 4 80W Pod Kit',
    price: 38500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=Nord4',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '2000mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=Nord4',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1876,
    totalFavorites: 387,
    weeklyViews: 319,
    brand: 'SMOK',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 3.9, body: 4.0, freshness: 0, totalReviewCount: 73 },
    sellers: [{ name: '베이프마켓', price: 38500, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 38500 }],
  },
  {
    id: 'device-004',
    name: '[VOOPOO] Drag Nano 2 Pod Kit',
    price: 29800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=DragNano2',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '800mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=DragNano2',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1456,
    totalFavorites: 298,
    weeklyViews: 247,
    brand: 'VOOPOO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 3.7, body: 3.8, freshness: 0, totalReviewCount: 52 },
    sellers: [{ name: '쿨베이퍼', price: 29800, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 29800 }],
  },
  {
    id: 'device-005',
    name: '[UWELL] Caliburn A2 Pod Kit',
    price: 35900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnA2',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '520mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnA2',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1923,
    totalFavorites: 412,
    weeklyViews: 412,
    brand: 'UWELL',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 0, menthol: 0, throatHit: 4.2, body: 4.1, freshness: 0, totalReviewCount: 78 },
    sellers: [{ name: '익스트림베이프', price: 35900, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 35900 }],
  },
  {
    id: 'device-006',
    name: '[GeekVape] Wenax Stylus Pod Kit',
    price: 27500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=WenaxStylus',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '400mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=WenaxStylus',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1134,
    totalFavorites: 234,
    weeklyViews: 234,
    brand: 'GeekVape',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 0, menthol: 0, throatHit: 3.6, body: 3.5, freshness: 0, totalReviewCount: 45 },
    sellers: [{ name: '베이프월드', price: 27500, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 27500 }],
  },
  {
    id: 'device-007',
    name: '[ASPIRE] Breeze NXT Pod Kit',
    price: 33200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=BreezeNXT',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '1000mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=BreezeNXT',
    productCategory: ProductCategory.DEVICE,
    totalViews: 987,
    totalFavorites: 198,
    weeklyViews: 198,
    brand: 'ASPIRE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 3.8, body: 3.9, freshness: 0, totalReviewCount: 41 },
    sellers: [{ name: '전자담배샵', price: 33200, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 33200 }],
  },
  {
    id: 'device-008',
    name: '[LOST VAPE] Ursa Nano Pod Kit',
    price: 39800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=UrsaNano',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '800mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=UrsaNano',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1567,
    totalFavorites: 334,
    weeklyViews: 334,
    brand: 'LOST VAPE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 0, menthol: 0, throatHit: 4.0, body: 4.2, freshness: 0, totalReviewCount: 63 },
    sellers: [{ name: '베이프마켓', price: 39800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 39800 }],
  },
  {
    id: 'device-009',
    name: '[INNOKIN] Klypse Pod Kit',
    price: 25900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=Klypse',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '700mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=Klypse',
    productCategory: ProductCategory.DEVICE,
    totalViews: 834,
    totalFavorites: 167,
    weeklyViews: 167,
    brand: 'INNOKIN',
    isAvailable: true,
    averageReviewInfo: { rating: 3.9, sweetness: 0, menthol: 0, throatHit: 3.4, body: 3.6, freshness: 0, totalReviewCount: 38 },
    sellers: [{ name: '쿨베이퍼', price: 25900, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 25900 }],
  },
  {
    id: 'device-010',
    name: '[OXVA] Xlim SE Pod Kit',
    price: 31500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=XlimSE',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '900mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=XlimSE',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1245,
    totalFavorites: 267,
    weeklyViews: 267,
    brand: 'OXVA',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 3.9, body: 4.0, freshness: 0, totalReviewCount: 56 },
    sellers: [{ name: '익스트림베이프', price: 31500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 31500 }],
  },

  // DL 기기 10개
  {
    id: 'device-011',
    name: '[VOOPOO] Drag X Plus 100W',
    price: 68000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=DragXPlus',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '5000mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=DragXPlus',
    productCategory: ProductCategory.DEVICE,
    totalViews: 2876,
    totalFavorites: 589,
    weeklyViews: 589,
    brand: 'VOOPOO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 0, menthol: 0, throatHit: 2.1, body: 4.8, freshness: 0, totalReviewCount: 123 },
    sellers: [{ name: '베이프월드', price: 68000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 68000 }],
  },
  {
    id: 'device-012',
    name: '[GeekVape] Aegis Legend 2 200W',
    price: 89500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=AegisLegend2',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=AegisLegend2',
    productCategory: ProductCategory.DEVICE,
    totalViews: 3245,
    totalFavorites: 698,
    weeklyViews: 698,
    brand: 'GeekVape',
    isAvailable: true,
    averageReviewInfo: { rating: 4.7, sweetness: 0, menthol: 0, throatHit: 1.8, body: 4.9, freshness: 0, totalReviewCount: 156 },
    sellers: [{ name: '전자담배샵', price: 89500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 89500 }],
  },
  {
    id: 'device-013',
    name: '[SMOK] MAG P3 230W Kit',
    price: 75800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=MAGP3',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=MAGP3',
    productCategory: ProductCategory.DEVICE,
    totalViews: 2134,
    totalFavorites: 445,
    weeklyViews: 445,
    brand: 'SMOK',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 2.0, body: 4.5, freshness: 0, totalReviewCount: 98 },
    sellers: [{ name: '베이프마켓', price: 75800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 75800 }],
  },
  {
    id: 'device-014',
    name: '[VAPORESSO] Gen 200 Kit',
    price: 82300,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=Gen200',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=Gen200',
    productCategory: ProductCategory.DEVICE,
    totalViews: 2789,
    totalFavorites: 567,
    weeklyViews: 567,
    brand: 'VAPORESSO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 0, menthol: 0, throatHit: 1.9, body: 4.7, freshness: 0, totalReviewCount: 134 },
    sellers: [{ name: '쿨베이퍼', price: 82300, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 82300 }],
  },
  {
    id: 'device-015',
    name: '[LOST VAPE] Centaurus B80 Kit',
    price: 95000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=CentaurusB80',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '싱글배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=CentaurusB80',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1876,
    totalFavorites: 398,
    weeklyViews: 398,
    brand: 'LOST VAPE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 0, menthol: 0, throatHit: 1.7, body: 4.8, freshness: 0, totalReviewCount: 87 },
    sellers: [{ name: '익스트림베이프', price: 95000, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 95000 }],
  },
  {
    id: 'device-016',
    name: '[Dovpo] Riva DNA250C 200W',
    price: 125000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=RivaDNA250C',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=RivaDNA250C',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1456,
    totalFavorites: 289,
    weeklyViews: 289,
    brand: 'Dovpo',
    isAvailable: true,
    averageReviewInfo: { rating: 4.8, sweetness: 0, menthol: 0, throatHit: 1.6, body: 4.9, freshness: 0, totalReviewCount: 67 },
    sellers: [{ name: '베이프월드', price: 125000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 125000 }],
  },
  {
    id: 'device-017',
    name: '[DRAG] S Pro 80W Kit',
    price: 55900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=DragSPro',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '3200mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=DragSPro',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1923,
    totalFavorites: 412,
    weeklyViews: 412,
    brand: 'DRAG',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 2.1, body: 4.3, freshness: 0, totalReviewCount: 89 },
    sellers: [{ name: '전자담배샵', price: 55900, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 55900 }],
  },
  {
    id: 'device-018',
    name: '[WISMEC] Reuleaux RX GEN3 300W',
    price: 98000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=ReuleauxRXGEN3',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '트리플배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=ReuleauxRXGEN3',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1567,
    totalFavorites: 334,
    weeklyViews: 334,
    brand: 'WISMEC',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 1.8, body: 4.6, freshness: 0, totalReviewCount: 76 },
    sellers: [{ name: '베이프마켓', price: 98000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 98000 }],
  },
  {
    id: 'device-019',
    name: '[IJOY] Captain PD270 Kit',
    price: 72500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=CaptainPD270',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=CaptainPD270',
    productCategory: ProductCategory.DEVICE,
    totalViews: 1234,
    totalFavorites: 267,
    weeklyViews: 267,
    brand: 'IJOY',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 0, menthol: 0, throatHit: 2.2, body: 4.2, freshness: 0, totalReviewCount: 54 },
    sellers: [{ name: '쿨베이퍼', price: 72500, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 72500 }],
  },
  {
    id: 'device-020',
    name: '[Tesla] WYE 200W Kit',
    price: 85600,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=WYE200W',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '듀얼배터리',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=WYE200W',
    productCategory: ProductCategory.DEVICE,
    totalViews: 987,
    totalFavorites: 198,
    weeklyViews: 198,
    brand: 'Tesla',
    isAvailable: true,
    averageReviewInfo: { rating: 3.9, sweetness: 0, menthol: 0, throatHit: 2.0, body: 4.1, freshness: 0, totalReviewCount: 43 },
    sellers: [{ name: '익스트림베이프', price: 85600, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 85600 }],
  },
];

// 코일/팟/기타 상품 20개
const accessoryProducts: ProductDetail[] = [
  // 코일 7개
  {
    id: 'accessory-001',
    name: '[VAPORESSO] GTX Coil 0.2ohm (5개입)',
    price: 18500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=GTXCoil',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=GTXCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 1456,
    totalFavorites: 298,
    weeklyViews: 298,
    brand: 'VAPORESSO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 87 },
    sellers: [{ name: '베이프월드', price: 18500, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 18500 }],
  },
  {
    id: 'accessory-002',
    name: '[SMOK] Nord Coil 0.6ohm (5개입)',
    price: 16800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=NordCoil',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=NordCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 2134,
    totalFavorites: 445,
    weeklyViews: 445,
    brand: 'SMOK',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 112 },
    sellers: [{ name: '전자담배샵', price: 16800, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 16800 }],
  },
  {
    id: 'accessory-003',
    name: '[UWELL] Caliburn Coil 1.0ohm (4개입)',
    price: 15200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnCoil',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '4개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 1876,
    totalFavorites: 387,
    weeklyViews: 387,
    brand: 'UWELL',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 98 },
    sellers: [{ name: '베이프마켓', price: 15200, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 15200 }],
  },
  {
    id: 'accessory-004',
    name: '[VOOPOO] PnP Coil 0.15ohm (5개입)',
    price: 19800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=PnPCoil',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=PnPCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 1345,
    totalFavorites: 267,
    weeklyViews: 267,
    brand: 'VOOPOO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 76 },
    sellers: [{ name: '쿨베이퍼', price: 19800, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 19800 }],
  },
  {
    id: 'accessory-005',
    name: '[GeekVape] B Series Coil 0.4ohm (5개입)',
    price: 17500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=BSeriesCoil',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=BSeriesCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 1123,
    totalFavorites: 234,
    weeklyViews: 234,
    brand: 'GeekVape',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 65 },
    sellers: [{ name: '익스트림베이프', price: 17500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 17500 }],
  },
  {
    id: 'accessory-006',
    name: '[ASPIRE] Nautilus Coil 1.6ohm (5개입)',
    price: 20500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=NautilusCoil',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=NautilusCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 987,
    totalFavorites: 198,
    weeklyViews: 198,
    brand: 'ASPIRE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 54 },
    sellers: [{ name: '베이프월드', price: 20500, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 20500 }],
  },
  {
    id: 'accessory-007',
    name: '[INNOKIN] Zenith Coil 1.2ohm (5개입)',
    price: 18900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=ZenithCoil',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '5개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=ZenithCoil',
    productCategory: ProductCategory.COIL,
    totalViews: 834,
    totalFavorites: 167,
    weeklyViews: 167,
    brand: 'INNOKIN',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 43 },
    sellers: [{ name: '전자담배샵', price: 18900, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 18900 }],
  },

  // 팟 7개
  {
    id: 'accessory-008',
    name: '[VAPORESSO] XROS Pod 2ml (2개입)',
    price: 12800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=XROSPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '2ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=XROSPod',
    productCategory: ProductCategory.POD,
    totalViews: 1678,
    totalFavorites: 345,
    weeklyViews: 345,
    brand: 'VAPORESSO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 89 },
    sellers: [{ name: '베이프마켓', price: 12800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 12800 }],
  },
  {
    id: 'accessory-009',
    name: '[SMOK] Nord Pod 3ml (3개입)',
    price: 14500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=NordPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '3ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=NordPod',
    productCategory: ProductCategory.POD,
    totalViews: 1456,
    totalFavorites: 298,
    weeklyViews: 298,
    brand: 'SMOK',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 67 },
    sellers: [{ name: '쿨베이퍼', price: 14500, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 14500 }],
  },
  {
    id: 'accessory-010',
    name: '[UWELL] Caliburn Pod 2ml (4개입)',
    price: 16200,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '2ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=CaliburnPod',
    productCategory: ProductCategory.POD,
    totalViews: 1923,
    totalFavorites: 412,
    weeklyViews: 412,
    brand: 'UWELL',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 102 },
    sellers: [{ name: '익스트림베이프', price: 16200, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 16200 }],
  },
  {
    id: 'accessory-011',
    name: '[VOOPOO] Drag Nano Pod 1ml (3개입)',
    price: 11900,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=DragNanoPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '1ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=DragNanoPod',
    productCategory: ProductCategory.POD,
    totalViews: 1234,
    totalFavorites: 256,
    weeklyViews: 256,
    brand: 'VOOPOO',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 78 },
    sellers: [{ name: '베이프월드', price: 11900, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 11900 }],
  },
  {
    id: 'accessory-012',
    name: '[GeekVape] Wenax Pod 2.5ml (2개입)',
    price: 13600,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=WenaxPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '2.5ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=WenaxPod',
    productCategory: ProductCategory.POD,
    totalViews: 987,
    totalFavorites: 201,
    weeklyViews: 201,
    brand: 'GeekVape',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 56 },
    sellers: [{ name: '전자담배샵', price: 13600, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 13600 }],
  },
  {
    id: 'accessory-013',
    name: '[LOST VAPE] Ursa Pod 3ml (2개입)',
    price: 15800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=UrsaPod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '3ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=UrsaPod',
    productCategory: ProductCategory.POD,
    totalViews: 1567,
    totalFavorites: 334,
    weeklyViews: 334,
    brand: 'LOST VAPE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 91 },
    sellers: [{ name: '베이프마켓', price: 15800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 15800 }],
  },
  {
    id: 'accessory-014',
    name: '[ASPIRE] Breeze Pod 2ml (5개입)',
    price: 17400,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=BreezePod',
    inhaleType: InhaleType.MTL,
    flavor: '무향',
    capacity: '2ml',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=BreezePod',
    productCategory: ProductCategory.POD,
    totalViews: 834,
    totalFavorites: 178,
    weeklyViews: 178,
    brand: 'ASPIRE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.0, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 45 },
    sellers: [{ name: '쿨베이퍼', price: 17400, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 17400 }],
  },

  // 기타 액세서리 6개
  {
    id: 'accessory-015',
    name: '[Samsung] 18650 배터리 3000mAh',
    price: 8500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=18650배터리',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '3000mAh',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=18650배터리',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 2345,
    totalFavorites: 456,
    weeklyViews: 456,
    brand: 'Samsung',
    isAvailable: true,
    averageReviewInfo: { rating: 4.6, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 134 },
    sellers: [{ name: '익스트림베이프', price: 8500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 8500 }],
  },
  {
    id: 'accessory-016',
    name: '[NITECORE] UM2 USB 배터리 충전기',
    price: 25800,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=UM2충전기',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '충전기',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=UM2충전기',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 1678,
    totalFavorites: 298,
    weeklyViews: 298,
    brand: 'NITECORE',
    isAvailable: true,
    averageReviewInfo: { rating: 4.5, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 87 },
    sellers: [{ name: '베이프월드', price: 25800, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 25800 }],
  },
  {
    id: 'accessory-017',
    name: '[VAPESOON] 코튼 위킹 소재 (10개입)',
    price: 4500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=코튼위킹',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '10개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=코튼위킹',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 1234,
    totalFavorites: 234,
    weeklyViews: 234,
    brand: 'VAPESOON',
    isAvailable: true,
    averageReviewInfo: { rating: 4.2, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 65 },
    sellers: [{ name: '전자담배샵', price: 4500, shippingFee: 3000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 4500 }],
  },
  {
    id: 'accessory-018',
    name: '[COIL MASTER] 521 Tab Pro 저항측정기',
    price: 35000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=521TabPro',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '측정기',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=521TabPro',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 987,
    totalFavorites: 167,
    weeklyViews: 167,
    brand: 'COIL MASTER',
    isAvailable: true,
    averageReviewInfo: { rating: 4.4, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 43 },
    sellers: [{ name: '베이프마켓', price: 35000, shippingFee: 2500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 35000 }],
  },
  {
    id: 'accessory-019',
    name: '[DEMON KILLER] 프리빌트 코일 (10개입)',
    price: 12000,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=프리빌트코일',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '10개',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=프리빌트코일',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 1456,
    totalFavorites: 287,
    weeklyViews: 287,
    brand: 'DEMON KILLER',
    isAvailable: true,
    averageReviewInfo: { rating: 4.1, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 76 },
    sellers: [{ name: '쿨베이퍼', price: 12000, shippingFee: 2000, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 12000 }],
  },
  {
    id: 'accessory-020',
    name: '[VAPEFLY] 가변전압 도구 킷',
    price: 28500,
    imageUrl: 'https://via.placeholder.com/300x300.png?text=도구킷',
    inhaleType: InhaleType.DL,
    flavor: '무향',
    capacity: '도구',
    thumbnailUrl: 'https://via.placeholder.com/300x300.png?text=도구킷',
    productCategory: ProductCategory.ACCESSORY,
    totalViews: 723,
    totalFavorites: 145,
    weeklyViews: 145,
    brand: 'VAPEFLY',
    isAvailable: true,
    averageReviewInfo: { rating: 4.3, sweetness: 0, menthol: 0, throatHit: 0, body: 0, freshness: 0, totalReviewCount: 54 },
    sellers: [{ name: '익스트림베이프', price: 28500, shippingFee: 3500, url: 'https://example.com' }],
    reviews: [],
    lowestPriceHistory: [{ date: '2024-01-01', price: 28500 }],
  },
];

// 모든 상품 데이터 합치기
export const allProducts: ProductDetail[] = [
  ...liquidProducts,
  ...deviceProducts, 
  ...accessoryProducts
];

// 카테고리별 상품 데이터
export const productsByCategory = {
  liquid: liquidProducts,
  device: deviceProducts,
  accessory: accessoryProducts,
  all: allProducts
};

// 호흡방식별 상품 데이터
export const productsByInhaleType = {
  MTL: allProducts.filter(p => p.inhaleType === InhaleType.MTL),
  DL: allProducts.filter(p => p.inhaleType === InhaleType.DL),
  all: allProducts
};

// 기존 호환성을 위한 export
export const mockProductDetails = allProducts;

// Product 타입으로만 데이터가 필요한 경우 (products 페이지용)
export const mockProducts: Product[] = allProducts.map(product => ({
  id: product.id,
  name: product.name,
  price: product.price,
  imageUrl: product.imageUrl,
  productCategory: product.productCategory,
  inhaleType: product.inhaleType,
  flavor: product.flavor,
  capacity: product.capacity,
  totalViews: product.totalViews,
  totalFavorites: product.totalFavorites,
  weeklyViews: product.weeklyViews,
  brand: product.brand,
  isAvailable: product.isAvailable,
}));

// 특정 상품 ID로 상품 상세 정보 조회 (기존 호환성을 위한 함수)
export const getProductDetail = (id: string): ProductDetail | undefined => {
  return allProducts.find(product => product.id === id);
};